- name: Setup Frontend
  hosts: all
  become: yes
  tasks:
    - name: Installing nginx Server
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: remove directory
      Ansible.builtin.file:
          Path: /urs/share/nginx/html
          State: absent



