- name: Demo on templates
  hosts: localhost
  connection: local
  vars:
    fruits:
      - name: apple
        quantity: 100
      - name: orange
        quantity: 200
  tasks:
    - name: Copy file
      ansible.builtin.template:
        src: text.txt
        dest: /tmp/test.txt